#pragma once

#undef  IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT

#undef  TAPPING_TERM
#define TAPPING_TERM 200

#undef  TAPPING_TERM_PER_KEY
#define TAPPING_TERM_PER_KEY

#undef QMK_KEYS_PER_SCAN
#define QMK_KEYS_PER_SCAN 4
