#pragma once

#undef IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT

#undef TAPPING_TERM
#define TAPPING_TERM 250

#undef RETRO_TAPPING
#define RETRO_TAPPING

#undef RETRO_TAPPING_PER_KEY
#define RETRO_TAPPING_PER_KEY

#undef COMBO_COUNT
#define COMBO_COUNT 2
